# -*- coding: utf-8 -*-
"""Ha tang chung cho icon ribbon T3Lab.

Dung boi ca `dev/build_icons.py` (sinh dark + render PNG) va
`dev/audit_icons.py` (gate). Khong chay truc tiep.

Chuan: docs/ui-governance/09-ribbon-icon-standard.md
"""

import json
import os
import re
import struct
import sys

# ── Duong dan ────────────────────────────────────────────────────────────
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
if os.path.dirname(HERE) not in sys.path:
    sys.path.insert(0, os.path.dirname(HERE))
from tabdir import TAB as TAB_DIR  # noqa: E402  (the tab folder name changes)
TOKENS_FILE = os.path.join(HERE, "tokens.json")
RENDER_JS = os.path.join(HERE, "render.js")

# ── Mien tru ─────────────────────────────────────────────────────────────
# 2026-09-11: Support panel KHONG con duoc mien tru ca panel nua. Moi tool do
# T3Lab lam deu di theo he chung. Chi con mien tru dung 4 bundle, moi cai co
# ly do rieng - xem muc 7 cua chuan.
EXEMPT_BUNDLES = {
    # Logo cua hang khac. Ve lai thanh line-art cua minh la vua mat nhan dien
    # vua dung vao nhan hieu cua ho.
    "Support.panel/CloudLinks.stack/Autodesk Forma.urlbutton",
    "Support.panel/CloudLinks.stack/Autodesk Health.urlbutton",
    "Support.panel/CloudLinks.stack/Bluebeam Status.urlbutton",
    # Mascot san pham. Cung ly do `T3LabAssistant.xaml` dang bi khoa UI:
    # day la be mat tro chuyen, khong phai mot cong cu Revit.
    "Support.panel/T3LabAssistant.pushbutton",
}

EXEMPT_REASON = ("3 logo hang khac (Forma / Health / Bluebeam) + mascot "
                 "T3LabAssistant - co chu dich, xem muc 7 cua chuan")

BUNDLE_SUFFIXES = (".pushbutton", ".pulldown", ".urlbutton", ".splitbutton",
                   ".splitpushbutton", ".smartbutton")

ICON_LIGHT_SVG = "icon.svg"
ICON_DARK_SVG = "icon.dark.svg"
ICON_LIGHT_PNG = "icon.png"
ICON_DARK_PNG = "icon.dark.png"

GENERATED_MARK = "GENERATED by dev/build_icons.py"

# ── Token ────────────────────────────────────────────────────────────────


def load_tokens():
    """Doc tokens.json -> (cfg, light_to_dark, light_set, name_by_light)."""
    with open(TOKENS_FILE, "r", encoding="utf-8") as fh:
        cfg = json.load(fh)
    light_to_dark = {}
    name_by_light = {}
    for name, pair in cfg["tokens"].items():
        light = pair["light"].upper()
        light_to_dark[light] = pair["dark"].upper()
        name_by_light[light] = name
    return cfg, light_to_dark, light_set(cfg), name_by_light


def light_set(cfg):
    return {p["light"].upper() for p in cfg["tokens"].values()}


HEX_RE = re.compile(r"#[0-9A-Fa-f]{6}\b")


def hexes_in(text):
    """Moi ma mau 6 ky tu xuat hien trong SVG, viet hoa."""
    return [m.group(0).upper() for m in HEX_RE.finditer(text)]


def to_dark(svg_text, light_to_dark):
    """Doi bang mau light -> dark trong MOT luot.

    Phai la mot luot: `deep` sinh ra #F3F3F3, ma #F3F3F3 lai la `surface` o
    ban light. Thay tuan tu se doi hai lan va lam hong mau.
    """
    def repl(match):
        return light_to_dark.get(match.group(0).upper(), match.group(0))
    return HEX_RE.sub(repl, svg_text)


# ── Quet bundle ──────────────────────────────────────────────────────────


class Bundle(object):
    """Mot nut tren ribbon co (hoac can co) icon."""

    def __init__(self, path):
        self.path = path
        self.rel = os.path.relpath(path, TAB_DIR).replace("\\", "/")
        self.name = os.path.basename(path)
        parts = self.rel.split("/")
        self.panel = parts[0]
        # Tier B = nam trong stack/pulldown, pyRevit ve o ICON_MEDIUM (24px).
        # Tier A = nut top-level cua panel, ICON_LARGE (32px).
        self.tier = "A" if len(parts) == 2 else "B"

    def file(self, name):
        return os.path.join(self.path, name)

    def has(self, name):
        return os.path.isfile(self.file(name))

    def read(self, name):
        with open(self.file(name), "r", encoding="utf-8") as fh:
            return fh.read()

    @property
    def label(self):
        return self.rel


def find_bundles(include_exempt=False):
    """Moi bundle duoi thu muc tab, tru cac bundle duoc mien tru."""
    out = []
    for root, dirs, _files in os.walk(TAB_DIR):
        dirs.sort()
        base = os.path.basename(root)
        if not base.endswith(BUNDLE_SUFFIXES):
            continue
        rel = os.path.relpath(root, TAB_DIR).replace("\\", "/")
        if not include_exempt and rel in EXEMPT_BUNDLES:
            continue
        out.append(Bundle(root))
    out.sort(key=lambda b: b.rel)
    return out


# ── PNG ──────────────────────────────────────────────────────────────────


def png_size(path):
    """(width, height) cua PNG, doc thang tu IHDR. None neu khong doc duoc."""
    try:
        with open(path, "rb") as fh:
            head = fh.read(33)
        if head[:8] != b"\x89PNG\r\n\x1a\n":
            return None
        return struct.unpack(">II", head[16:24])
    except (IOError, OSError, struct.error):
        return None


VIEWBOX_RE = re.compile(r'viewBox\s*=\s*"([^"]*)"')
CANONICAL_VIEWBOX = "0 0 32 32"


def viewbox(svg_text):
    m = VIEWBOX_RE.search(svg_text)
    return " ".join(m.group(1).split()) if m else None


def is_migrated(svg_text, allowed=None):
    """True khi icon da chuyen sang chuan moi.

    Dau hieu la `viewBox="0 0 32 32"`: he cu ve tren luoi 64, he moi tren 32.
    Co tinh KHONG dung bang mau lam dau hieu - neu vay, chi can them mot ma
    mau la la icon tu dong thoat khoi moi luat con lai.

    `allowed` giu lai cho tuong thich, khong dung nua.
    """
    return viewbox(svg_text) == CANONICAL_VIEWBOX
