# -*- coding: utf-8 -*-
"""
T3Lab Pattern Maker Engine
==========================
Modernized AutoCAD .pat & Revit FillPattern compiler.
Calculates safe grids, offsets, shifts, and dash segments for seamless tiling.
Compatible with CPython 3 and Revit 2021-2026.
"""

import io
import math
import os
import re
import time
from math import sqrt, pi, sin, cos, degrees, atan2
from Snippets._compat import disposing

# Fallback logger
try:
    from pyrevit import script
    logger = script.get_logger()
except Exception:
    import logging
    logger = logging.getLogger("T3Lab.Pattern")

# Optional Revit API imports (only active when running inside Revit)
try:
    from Autodesk.Revit import DB
    from pyrevit import revit, HOST_APP
    from System.Collections.Generic import List as ClrList
    HAS_REVIT = True
except Exception:
    DB = None
    revit = None
    HOST_APP = None
    ClrList = list
    HAS_REVIT = False


PI = pi
HALF_PI = PI / 2.0
TWO_PI = PI * 2.0
ZERO_TOL = 1e-6
COORD_RESOLUTION = 8

MAX_MODEL_DOMAIN = 100.0  # feet
MAX_DETAIL_DOMAIN = 10.0
MAX_DOMAIN_MULT = 8
RATIO_RESOLUTION = 2
ANGLE_CORR_RATIO = 0.01

PAT_SEPARATOR = ', '
PAT_FILE_TEMPLATE = (
    "; Written by T3Lab Make Pattern\n"
    "; Date: {date} {time}\n"
    ";---------------------------------------------------------------------\n"
    ";%UNITS={units}\n"
    "*{name}, generated by T3Lab\n"
    ";%TYPE={type}\n"
)


def round_coord(val):
    return 0.0 if abs(val) < ZERO_TOL else round(val, COORD_RESOLUTION)


def format_pat_num(val):
    """Format floating number for PAT file output cleanly without unnecessary zeros."""
    val = round_coord(val)
    if abs(val - round(val)) < 1e-7:
        return "{:.1f}".format(float(round(val)))
    formatted = "{:.6f}".format(val).rstrip('0')
    if formatted.endswith('.'):
        formatted += '0'
    return formatted


class PatternPoint(object):
    __slots__ = ('u', 'v')

    def __init__(self, u, v):
        self.u = round_coord(float(u))
        self.v = round_coord(float(v))

    def __repr__(self):
        return "<PatternPoint U:{:.4f} V:{:.4f}>".format(self.u, self.v)

    def __eq__(self, other):
        if not isinstance(other, PatternPoint):
            return False
        return abs(self.u - other.u) < ZERO_TOL and abs(self.v - other.v) < ZERO_TOL

    def __hash__(self):
        return hash((round(self.u, 5), round(self.v, 5)))

    def __add__(self, other):
        return PatternPoint(self.u + other.u, self.v + other.v)

    def __sub__(self, other):
        return PatternPoint(self.u - other.u, self.v - other.v)

    def distance_to(self, other):
        return sqrt((other.u - self.u) ** 2 + (other.v - self.v) ** 2)

    def rotate(self, angle_rad, origin=None):
        ox = origin.u if origin else 0.0
        oy = origin.v if origin else 0.0
        tu = self.u - ox
        tv = self.v - oy
        ca = cos(angle_rad)
        sa = sin(angle_rad)
        self.u = round_coord(ox + (tu * ca - tv * sa))
        self.v = round_coord(oy + (tu * sa + tv * ca))
        return self


class PatternLine(object):
    def __init__(self, start_p, end_p):
        # Normalize: start point has lower or equal V, or lower U if V is equal
        if start_p.v < end_p.v or (abs(start_p.v - end_p.v) < ZERO_TOL and start_p.u <= end_p.u):
            self.start_point = PatternPoint(start_p.u, start_p.v)
            self.end_point = PatternPoint(end_p.u, end_p.v)
        else:
            self.start_point = PatternPoint(end_p.u, end_p.v)
            self.end_point = PatternPoint(start_p.u, start_p.v)

    def __repr__(self):
        return "<PatternLine Start:({:.3f},{:.3f}) End:({:.3f},{:.3f}) Len:{:.3f} Ang:{:.2f}deg>".format(
            self.start_point.u, self.start_point.v,
            self.end_point.u, self.end_point.v,
            self.length, degrees(self.angle)
        )

    @property
    def direction(self):
        return PatternPoint(self.end_point.u - self.start_point.u,
                            self.end_point.v - self.start_point.v)

    @property
    def angle(self):
        """Angle in radians [0, pi). Standard positive angle against +U axis."""
        du = self.end_point.u - self.start_point.u
        dv = self.end_point.v - self.start_point.v
        ang = atan2(dv, du)
        if ang < -ZERO_TOL:
            ang += PI
        elif abs(ang - PI) < ZERO_TOL:
            ang = 0.0
        return round_coord(ang)

    @property
    def center_point(self):
        return PatternPoint((self.start_point.u + self.end_point.u) / 2.0,
                            (self.start_point.v + self.end_point.v) / 2.0)

    @property
    def length(self):
        return sqrt((self.end_point.u - self.start_point.u) ** 2 +
                    (self.end_point.v - self.start_point.v) ** 2)

    def point_on_line(self, point, tol=ZERO_TOL):
        a = self.start_point
        b = self.end_point
        c = point
        cross = (b.u - a.u) * (c.v - a.v) - (b.v - a.v) * (c.u - a.u)
        if abs(cross) > tol * (self.length + 1.0):
            return False
        # Check within segment bounds with tolerance
        min_u = min(a.u, b.u) - tol
        max_u = max(a.u, b.u) + tol
        min_v = min(a.v, b.v) - tol
        max_v = max(a.v, b.v) + tol
        return (min_u <= c.u <= max_u) and (min_v <= c.v <= max_v)

    def rotate(self, angle_rad, origin=None):
        self.start_point.rotate(angle_rad, origin)
        self.end_point.rotate(angle_rad, origin)


class PatternSafeGrid(object):
    """
    Computes valid repeating parameters (Span, Offset, Shift) for a line family
    traversing through a repeating domain (W x H) under given (u_tiles, v_tiles).
    """
    def __init__(self, domain_bounds, diag_angle, u_tiles, v_tiles, flipped=False):
        self._bounds = domain_bounds
        self._flipped = flipped
        self._diag_angle = diag_angle
        self._axis_line = PatternLine(
            PatternPoint(0, 0),
            PatternPoint(domain_bounds.u * u_tiles, domain_bounds.v * v_tiles)
        )
        self._determine_params(u_tiles, v_tiles)

    def _determine_params(self, u_tiles, v_tiles):
        if self._axis_line.angle <= self._diag_angle:
            self._offset_direction = 1.0 if self._flipped else -1.0
            self._angle = self._axis_line.angle
            self._u_tiles = u_tiles
            self._v_tiles = v_tiles
            self._domain_u = self._bounds.u
            self._domain_v = self._bounds.v
        else:
            self._offset_direction = -1.0 if self._flipped else 1.0
            self._angle = (self._axis_line.angle - HALF_PI) if self._flipped else (HALF_PI - self._axis_line.angle)
            self._u_tiles = v_tiles
            self._v_tiles = u_tiles
            self._domain_u = self._bounds.v
            self._domain_v = self._bounds.u

    @property
    def grid_angle(self):
        return (PI - self._axis_line.angle) if self._flipped else self._axis_line.angle

    @property
    def span(self):
        return self._axis_line.length

    @property
    def offset(self):
        if abs(self._angle) < ZERO_TOL:
            return self._domain_v * self._offset_direction
        return abs(self._domain_u * sin(self._angle) / max(1, self._v_tiles)) * self._offset_direction

    @property
    def shift(self):
        if abs(self._angle) < ZERO_TOL:
            return 0.0

        if self._u_tiles == self._v_tiles == 1:
            return abs(self._domain_u * cos(self._angle))

        # Abstract offset axis search
        off_u = abs(self.offset * sin(self._angle))
        off_v = -abs(self.offset * cos(self._angle))
        offset_vec = PatternPoint(off_u, off_v)

        axis_start = PatternPoint(0, 0) + offset_vec
        axis_end = PatternPoint(self._domain_u * self._u_tiles, self._domain_v * self._v_tiles) + offset_vec
        offset_axis = PatternLine(axis_start, axis_end)

        for u_mult in range(self._u_tiles + 1):
            for v_mult in range(self._v_tiles + 1):
                pt = PatternPoint(self._domain_u * u_mult, self._domain_v * v_mult)
                if offset_axis.point_on_line(pt, tol=1e-4):
                    return offset_axis.start_point.distance_to(pt)

        return None

    def is_valid(self):
        return self.shift is not None


class PatternDomain(object):
    """Encapsulates the (0,0) -> (W,H) module domain and calculates safe angle grids."""
    def __init__(self, width, height, is_model=True, expandable=True):
        self.width = max(1e-4, float(width))
        self.height = max(1e-4, float(height))
        self._bounds = PatternPoint(self.width, self.height)
        self.is_model = is_model
        self.expandable = expandable
        self._max_domain = MAX_MODEL_DOMAIN if is_model else MAX_DETAIL_DOMAIN
        self._target_domain = self._max_domain
        self.diagonal = PatternLine(PatternPoint(0, 0), self._bounds)
        self.safe_angles = []
        self._calculate_safe_angles()

    @property
    def bounds(self):
        return self._bounds

    def _calculate_safe_angles(self):
        self.safe_angles = []
        diag_ang = self.diagonal.angle

        # Standard orthogonal and diagonal angles
        self.safe_angles.append(PatternSafeGrid(self._bounds, diag_ang, 1, 0, False))
        self.safe_angles.append(PatternSafeGrid(self._bounds, diag_ang, 1, 0, True))
        self.safe_angles.append(PatternSafeGrid(self._bounds, diag_ang, 1, 1, False))
        self.safe_angles.append(PatternSafeGrid(self._bounds, diag_ang, 1, 1, True))
        self.safe_angles.append(PatternSafeGrid(self._bounds, diag_ang, 0, 1, False))

        # Ratio search
        processed_ratios = {1.0}
        u_mult = 1
        limit = max(10, int(self._target_domain / max(self.width, self.height, 1.0)))

        while u_mult <= limit:
            v_mult = 1
            while v_mult <= limit:
                ratio = round(v_mult / float(u_mult), RATIO_RESOLUTION)
                if ratio not in processed_ratios:
                    ag1 = PatternSafeGrid(self._bounds, diag_ang, u_mult, v_mult, False)
                    ag2 = PatternSafeGrid(self._bounds, diag_ang, u_mult, v_mult, True)
                    if ag1.is_valid() and ag2.is_valid():
                        self.safe_angles.append(ag1)
                        self.safe_angles.append(ag2)
                        processed_ratios.add(ratio)
                v_mult += 1
            u_mult += 1

    def get_best_grid(self, axis_angle):
        norm_ang = axis_angle % PI
        return min(self.safe_angles, key=lambda g: abs((g.grid_angle % PI) - norm_ang))


class PatternGrid(object):
    """A family of parallel lines with defined origin, angle, shift, offset, and dash segments."""
    def __init__(self, angle_rad, origin, offset, shift, segments=None):
        self.angle = round_coord(angle_rad % PI)
        self.origin = origin
        self.offset = round_coord(offset)
        self.shift = round_coord(shift)
        self.segments = segments or []

    def __repr__(self):
        return "<PatternGrid Ang:{:.2f}deg Orig:({:.2f},{:.2f}) Off:{:.2f} Shift:{:.2f} Segs:{}>".format(
            degrees(self.angle), self.origin.u, self.origin.v,
            self.offset, self.shift, self.segments
        )


class PatternCompiler(object):
    """
    Compiles arbitrary line segments inside a module [0, W] x [0, H]
    into an AutoCAD .pat string and/or Revit FillPattern.
    """
    def __init__(self, name, width, height, is_model=True, shift_ratio=0.0):
        self.name = re.sub(r'[\r\n\t,;]', '_', name.strip()) or "T3_Custom_Pattern"
        self.width = float(width)
        self.height = float(height)
        self.is_model = is_model
        self.shift_ratio = float(shift_ratio)  # e.g. 0.0 (stack), 0.5 (running bond 1/2), 0.333
        self.domain = PatternDomain(self.width, self.height, is_model=is_model)
        self.grids = []

    def compile_lines(self, lines):
        """
        Takes lines as list of tuples [((x1, y1), (x2, y2)), ...] in module units (mm).
        Processes them into PatternGrid families.
        """
        self.grids = []
        if not lines:
            return self.grids

        # Group lines by approximate angle
        angle_groups = {}
        for (p1, p2) in lines:
            sp = PatternPoint(p1[0], p1[1])
            ep = PatternPoint(p2[0], p2[1])
            pline = PatternLine(sp, ep)
            if pline.length < ZERO_TOL:
                continue

            # Snap to safe angle
            safe_grid = self.domain.get_best_grid(pline.angle)
            snapped_angle = safe_grid.grid_angle

            # Group key by angle in degrees rounded to 1 decimal place
            ang_key = round(degrees(snapped_angle) % 180.0, 1)
            if ang_key not in angle_groups:
                angle_groups[ang_key] = {
                    'safe_grid': safe_grid,
                    'lines': []
                }
            angle_groups[ang_key]['lines'].append(pline)

        for ang_key, grp in angle_groups.items():
            safe_grid = grp['safe_grid']
            ang = safe_grid.grid_angle
            offset = safe_grid.offset
            shift = safe_grid.shift

            # Apply user shift_ratio if the line is strictly horizontal or vertical
            if abs(ang) < 1e-4 or abs(ang - PI) < 1e-4:
                # Horizontal line: offset = height, shift = width * shift_ratio
                offset = self.height
                shift = self.width * self.shift_ratio
            elif abs(ang - HALF_PI) < 1e-4:
                # Vertical line: offset = width, shift = height * shift_ratio
                offset = self.width
                shift = self.height * self.shift_ratio

            # Calculate dash segments for lines in this group
            for pl in grp['lines']:
                # Find line length and repetition span
                span = safe_grid.span if safe_grid.span > pl.length else self.width
                pen_down = pl.length
                pen_up = max(0.0, span - pen_down)

                segs = [round_coord(pen_down)]
                if pen_up > ZERO_TOL:
                    segs.append(round_coord(pen_up))

                orig = PatternPoint(pl.start_point.u, pl.start_point.v)
                pgrid = PatternGrid(ang, orig, offset, shift, segs)
                self.grids.append(pgrid)

        return self.grids

    def to_pat_string(self, unit='MM'):
        """Generates standard AutoCAD / Revit .pat file format string."""
        scale_mult = 1.0 if unit.upper() == 'MM' else (1.0 / 25.4)
        pat_type = "MODEL" if self.is_model else "DRAFTING"
        cur_date = time.strftime("%Y-%m-%d")
        cur_time = time.strftime("%H:%M:%S")

        output = PAT_FILE_TEMPLATE.format(
            date=cur_date,
            time=cur_time,
            units=unit.upper(),
            name=self.name,
            type=pat_type
        )

        for g in self.grids:
            ang_deg = degrees(g.angle)
            ou = g.origin.u * scale_mult
            ov = g.origin.v * scale_mult
            sh = g.shift * scale_mult
            off = g.offset * scale_mult

            row = [
                format_pat_num(ang_deg),
                format_pat_num(ou),
                format_pat_num(ov),
                format_pat_num(sh),
                format_pat_num(off)
            ]

            if g.segments:
                for idx, seg in enumerate(g.segments):
                    s_val = seg * scale_mult
                    if idx % 2 != 0:
                        s_val = -abs(s_val)  # space is negative in .pat format
                    row.append(format_pat_num(s_val))

            output += PAT_SEPARATOR.join(row) + "\n"

        return output

    def create_revit_pattern(self, doc=None, create_filled_region=False):
        """Creates or updates DB.FillPatternElement in current Revit Document."""
        if not HAS_REVIT or not DB:
            raise RuntimeError("Revit API is not available in current environment.")

        doc = doc or revit.doc
        if not doc:
            raise RuntimeError("No active Revit Document found.")

        # Scale from mm to Revit internal units (FEET): 1 mm = 1 / 304.8 ft
        mm_to_feet = 1.0 / 304.8

        rvt_grids = []
        for g in self.grids:
            fg = DB.FillGrid()
            fg.Angle = g.angle
            fg.Origin = DB.UV(g.origin.u * mm_to_feet, g.origin.v * mm_to_feet)
            fg.Offset = g.offset * mm_to_feet
            fg.Shift = g.shift * mm_to_feet

            if g.segments:
                seg_list = ClrList[float]()
                for idx, seg in enumerate(g.segments):
                    val = seg * mm_to_feet
                    if idx % 2 != 0:
                        val = -abs(val)
                    seg_list.Add(val)
                fg.SetSegments(seg_list)

            rvt_grids.append(fg)

        fp_target = DB.FillPatternTarget.Model if self.is_model else DB.FillPatternTarget.Drafting
        fill_pat = DB.FillPattern(self.name, fp_target, DB.FillPatternHostOrientation.ToHost)
        fill_pat.SetFillGrids(ClrList[DB.FillGrid](rvt_grids))

        # Check existing FillPatternElement
        collector = DB.FilteredElementCollector(doc).OfClass(DB.FillPatternElement)
        target_fpe = None
        for elem in collector:
            existing_fp = elem.GetFillPattern()
            if existing_fp and existing_fp.Name == self.name and existing_fp.Target == fp_target:
                target_fpe = elem
                break

        with disposing(DB.Transaction(doc, "T3Lab: Make Pattern")) as t:
            t.Start()
            try:
                if target_fpe:
                    target_fpe.SetFillPattern(fill_pat)
                    fpe_result = target_fpe
                else:
                    fpe_result = DB.FillPatternElement.Create(doc, fill_pat)

                if create_filled_region and fpe_result:
                    self._create_filled_region_type(doc, self.name, fpe_result.Id)

                t.Commit()
                return fpe_result
            except Exception as ex:
                t.RollBack()
                raise ex

    def _create_filled_region_type(self, doc, name, pattern_id):
        """Duplicates an existing FilledRegionType and assigns the new pattern."""
        fr_collector = DB.FilteredElementCollector(doc).OfClass(DB.FilledRegionType)
        first_fr = fr_collector.FirstElement()
        if not first_fr:
            return

        # Check if type name exists
        for fr in fr_collector:
            fr_name = DB.Element.Name.__get__(fr)
            if fr_name == name:
                # Update existing
                if HOST_APP and HOST_APP.is_newer_than(2018):
                    fr.ForegroundPatternId = pattern_id
                else:
                    fr.FillPatternId = pattern_id
                return fr

        new_fr = first_fr.Duplicate(name)
        if HOST_APP and HOST_APP.is_newer_than(2018):
            new_fr.ForegroundPatternId = pattern_id
        else:
            new_fr.FillPatternId = pattern_id
        return new_fr


def make_pattern(name, lines, width, height, is_model=True, shift_ratio=0.0,
                 doc=None, create_filled_region=False):
    """Helper function to compile lines and create Revit pattern directly."""
    compiler = PatternCompiler(name, width, height, is_model=is_model, shift_ratio=shift_ratio)
    compiler.compile_lines(lines)
    return compiler.create_revit_pattern(doc=doc, create_filled_region=create_filled_region)


def export_pattern_to_file(file_path, name, lines, width, height,
                           is_model=True, shift_ratio=0.0, unit='MM'):
    """Helper function to compile lines and export .pat file."""
    compiler = PatternCompiler(name, width, height, is_model=is_model, shift_ratio=shift_ratio)
    compiler.compile_lines(lines)
    pat_str = compiler.to_pat_string(unit=unit)
    with io.open(file_path, 'w', encoding='utf-8') as f:
        f.write(pat_str)
    return file_path
